name: Deploy to BETA

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    name: Deploy to BETA
    runs-on: ubuntu-latest
    concurrency:
      group: beta-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt secrets
        env:
          SOPS_VERSION: v3.8.1
          SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
        shell: bash
        run: |
          wget -q -O sops https://github.com/getsops/sops/releases/download/${{ env.SOPS_VERSION }}/sops-${{ env.SOPS_VERSION }}.linux.amd64
          chmod +x ./sops
          ./sops --version
          ./sops -d ./firebase.enc > firebase.json
          rm -f firebase.enc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JACEM_CHAIEB }}'
          projectId: jacem-chaieb
          channelId: beta
          expires: 1d
      - run: 'rm -f firebase.json'
