name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build_deploy_hosting:
    name: Build & Deploy Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - run: 'echo "$REDIRECTS_JSON" > redirects.json'
        shell: bash
        env:
          REDIRECTS_JSON: ${{secrets.REDIRECTS_JSON}}

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - run: npm run build-json

      - name: Deploy to PROD
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:jc-tn-url-shortener
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to BETA
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy --only jc-tn-url-shortener beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Inject slug/short variables
        if: ${{ github.event_name == 'pull_request' }}
        uses: rlespinasse/github-slug-action@v3.x
      - name: Deploy to tmp url
        if: ${{ github.event_name == 'pull_request' }}
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy --only jc-tn-url-shortener --expires 1d ${{ env.GITHUB_HEAD_REF_SLUG_URL }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Clean up
        run: 'rm -rf redirects.json firebase.json'
        shell: bash
