name: Deploy to PRODUCTION
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secrets
        env:
          SOPS_VERSION: v3.7.3
          SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
        shell: bash
        run: |
          wget -q -O sops https://github.com/mozilla/sops/releases/download/${{ env.SOPS_VERSION }}/sops-${{ env.SOPS_VERSION }}.linux
          chmod +x ./sops
          ./sops --version
          ./sops -d ./firebase.enc > firebase.json
          rm -f firebase.enc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JACEM_CHAIEB }}'
          channelId: live
          projectId: jacem-chaieb
      - run: 'rm -f firebase.json'
