name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secrets
        env:
          SOPS_VERSION: v3.7.3
          SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
        shell: bash
        run: |
          wget -q -O sops https://github.com/mozilla/sops/releases/download/${{ env.SOPS_VERSION }}/sops-${{ env.SOPS_VERSION }}.linux
          chmod +x ./sops
          ./sops --version
          ./sops -d ./firebase.enc.json > firebase.json
          rm -f firebase.enc.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JACEM_CHAIEB }}'
          projectId: jacem-chaieb
      - run: 'rm -f firebase.json'
