name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths-ignore:
      - '**docker**'
      - '.github/**'
      - '.vscode/**'

jobs:
  build_and_preview:
    name: Deploy to Firebase Hosting on PR
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    concurrency:
      group: beta-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        env:
          SOPS_VERSION: v3.8.1
          SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
        shell: bash
        run: |
          wget -q -O sops https://github.com/getsops/sops/releases/download/${{ env.SOPS_VERSION }}/sops-${{ env.SOPS_VERSION }}.linux.amd64
          chmod +x ./sops
          ./sops --version
          ./sops -d ./firebase.enc > firebase.json
          rm -f firebase.enc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JACEM_CHAIEB }}'
          projectId: jacem-chaieb
      - run: 'rm -f firebase.json'
